[project]
name = "scib"
version = "0.1.0"
description = "Add a short description here"
authors = ["tpob <tpob@tpob.xyz>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "3.10.0"

[tasks]
postinstall = "pip install --no-build-isolation --no-deps -e ."

[dependencies]
scikit-learn = "1.3.2.*"
llvmlite = "0.41.1.*"
pandas = "<=2"
seaborn = "0.12.2.*"
scipy = "1.11.4.*"
deprecated = "1.2.14.*"
pydot = "1.4.2.*"
matplotlib = "<=3.6"
leidenalg = "0.10.1.*"
scanpy = ">=1.5"
h5py = "3.10.0.*"
igraph = ">=0.10"
anndata = ">=0.7.2"
scikit-misc = "0.1.4.*"
numpy = "1.26.2.*"
umap-learn = "0.5.5.*"

[host-dependencies]
python = ">=3.7"
setuptools = "68.2.2.*"
pip = "23.3.1.*"
wheel = "0.42.0.*"

[target.linux-64.build-dependencies]
gcc = ">=5"

